import type {
  SectionType,
  TechItem,
  Template,
  HeroData,
  AboutData,
  TechStackData,
  FeaturesData,
  GitHubWidgetsData,
  SocialData,
  VisitorCounterData,
  TrophiesData,
  SupportData,
  FunComponentsData,
} from "@/types";

export const APP_NAME = "RepoCanvas";
export const APP_TAGLINE = "Build beautiful GitHub READMEs without manually writing Markdown.";

export const SECTION_TYPES: Record<
  SectionType,
  { label: string; description: string; icon: string }
> = {
  hero: {
    label: "Hero",
    description: "Tagline and subtitle for your README",
    icon: "Rocket",
  },
  about: {
    label: "About",
    description: "About this project section",
    icon: "FileText",
  },
  "tech-stack": {
    label: "Tech Stack",
    description: "Technologies and tools you use",
    icon: "Wrench",
  },
  features: {
    label: "Features",
    description: "Key features of your project",
    icon: "LayoutGrid",
  },
  "github-widgets": {
    label: "GitHub Widgets",
    description: "Stats, streaks, and activity graphs",
    icon: "BarChart3",
  },
  social: {
    label: "Social",
    description: "Connect with you across platforms",
    icon: "Users",
  },
  "visitor-counter": {
    label: "Visitor Counter",
    description: "Show how many people viewed your profile",
    icon: "Eye",
  },
  trophies: {
    label: "Trophies",
    description: "GitHub achievement trophies",
    icon: "Trophy",
  },
  support: {
    label: "Support",
    description: "Donation and support links",
    icon: "Heart",
  },
  "fun-components": {
    label: "Fun",
    description: "Random memes and quotes",
    icon: "Sparkles",
  },
};

export const TECHNOLOGIES: TechItem[] = [
  { name: "TypeScript", icon: "typescript" },
  { name: "JavaScript", icon: "javascript" },
  { name: "Python", icon: "python" },
  { name: "Java", icon: "java" },
  { name: "Go", icon: "go" },
  { name: "Rust", icon: "rust" },
  { name: "C", icon: "c" },
  { name: "C++", icon: "cplusplus" },
  { name: "C#", icon: "csharp" },
  { name: "Swift", icon: "swift" },
  { name: "Kotlin", icon: "kotlin" },
  { name: "Ruby", icon: "ruby" },
  { name: "PHP", icon: "php" },
  { name: "Scala", icon: "scala" },
  { name: "Elixir", icon: "elixir" },
  { name: "Haskell", icon: "haskell" },
  { name: "Lua", icon: "lua" },
  { name: "R", icon: "r" },
  { name: "Dart", icon: "dart" },
  { name: "MATLAB", icon: "matlab" },
  { name: "Shell", icon: "shell" },
  { name: "PowerShell", icon: "powershell" },
  { name: "SQL", icon: "sql" },
  { name: "HTML", icon: "html" },
  { name: "CSS", icon: "css" },
  { name: "Sass", icon: "sass" },
  { name: "React", icon: "react" },
  { name: "Next.js", icon: "nextdotjs" },
  { name: "Vue.js", icon: "vuedotjs" },
  { name: "Angular", icon: "angular" },
  { name: "Svelte", icon: "svelte" },
  { name: "Astro", icon: "astro" },
  { name: "Node.js", icon: "nodedotjs" },
  { name: "Express", icon: "express" },
  { name: "Django", icon: "django" },
  { name: "Flask", icon: "flask" },
  { name: "FastAPI", icon: "fastapi" },
  { name: "Spring Boot", icon: "springboot" },
  { name: "Rails", icon: "rubyonrails" },
  { name: "ASP.NET", icon: "dotnet" },
  { name: "Laravel", icon: "laravel" },
  { name: "GraphQL", icon: "graphql" },
  { name: "Docker", icon: "docker" },
  { name: "Kubernetes", icon: "kubernetes" },
  { name: "AWS", icon: "amazonwebservices" },
  { name: "Firebase", icon: "firebase" },
  { name: "Vercel", icon: "vercel" },
  { name: "Netlify", icon: "netlify" },
  { name: "Heroku", icon: "heroku" },
  { name: "DigitalOcean", icon: "digitalocean" },
  { name: "Google Cloud", icon: "googlecloud" },
  { name: "Azure", icon: "microsoftazure" },
  { name: "PostgreSQL", icon: "postgresql" },
  { name: "MySQL", icon: "mysql" },
  { name: "SQLite", icon: "sqlite" },
  { name: "MongoDB", icon: "mongodb" },
  { name: "Redis", icon: "redis" },
  { name: "Supabase", icon: "supabase" },
  { name: "Prisma", icon: "prisma" },
  { name: "Tailwind CSS", icon: "tailwindcss" },
  { name: "Bootstrap", icon: "bootstrap" },
  { name: "Material UI", icon: "mui" },
  { name: "Flutter", icon: "flutter" },
  { name: "React Native", icon: "react" },
  { name: "Electron", icon: "electron" },
  { name: "Git", icon: "git" },
  { name: "GitHub", icon: "github" },
  { name: "GitLab", icon: "gitlab" },
  { name: "Bitbucket", icon: "bitbucket" },
  { name: "VS Code", icon: "visualstudiocode" },
  { name: "Neovim", icon: "neovim" },
  { name: "Vim", icon: "vim" },
  { name: "IntelliJ", icon: "intellijidea" },
  { name: "Postman", icon: "postman" },
  { name: "Jest", icon: "jest" },
  { name: "Vitest", icon: "vitest" },
  { name: "Cypress", icon: "cypress" },
  { name: "Playwright", icon: "playwright" },
  { name: "Webpack", icon: "webpack" },
  { name: "Vite", icon: "vite" },
  { name: "ESBuild", icon: "esbuild" },
  { name: "Turborepo", icon: "turborepo" },
  { name: "Gradle", icon: "gradle" },
  { name: "Maven", icon: "apachemaven" },
  { name: "NPM", icon: "npm" },
  { name: "Yarn", icon: "yarn" },
  { name: "pnpm", icon: "pnpm" },
  { name: "Notion", icon: "notion" },
  { name: "Jira", icon: "jira" },
  { name: "Figma", icon: "figma" },
  { name: "Linux", icon: "linux" },
  { name: "Windows", icon: "windows" },
  { name: "macOS", icon: "apple" },
  { name: "Android", icon: "android" },
  { name: "iOS", icon: "apple" },
  { name: "Nginx", icon: "nginx" },
  { name: "Apache", icon: "apache" },
  { name: "Elasticsearch", icon: "elasticsearch" },
  { name: "RabbitMQ", icon: "rabbitmq" },
  { name: "Kafka", icon: "apachekafka" },
  { name: "gRPC", icon: "grpc" },
  { name: "WebSocket", icon: "socketdotio" },
  { name: "REST API", icon: "fastapi" },
  { name: "OAuth", icon: "oauth" },
  { name: "JWT", icon: "jsonwebtokens" },
  { name: "WebAssembly", icon: "webassembly" },
  { name: "Rollup", icon: "rollupdotjs" },
  { name: "Parcel", icon: "parcel" },
  { name: "Snowpack", icon: "snowpack" },
  { name: "Gatsby", icon: "gatsby" },
  { name: "Remix", icon: "remix" },
  { name: "Nuxt.js", icon: "nuxtdotjs" },
  { name: "SolidJS", icon: "solid" },
  { name: "Qwik", icon: "qwik" },
  { name: "Alpine.js", icon: "alpinedotjs" },
  { name: "jQuery", icon: "jquery" },
  { name: "Backbone.js", icon: "backbone" },
  { name: "Ember.js", icon: "emberdotjs" },
  { name: "Meteor", icon: "meteor" },
  { name: "Strapi", icon: "strapi" },
  { name: "Contentful", icon: "contentful" },
  { name: "Sanity", icon: "sanity" },
  { name: "Payload CMS", icon: "payloadcms" },
  { name: "Ghost", icon: "ghost" },
  { name: "WordPress", icon: "wordpress" },
  { name: "Shopify", icon: "shopify" },
  { name: "WooCommerce", icon: "woocommerce" },
  { name: "Stripe", icon: "stripe" },
  { name: "PayPal", icon: "paypal" },
  { name: "Twilio", icon: "twilio" },
  { name: "SendGrid", icon: "twilio" },
  { name: "Cloudflare", icon: "cloudflare" },
  { name: "Linode", icon: "linode" },
  { name: "Vultr", icon: "vultr" },
  { name: "Hetzner", icon: "hetzner" },
  { name: "Deno", icon: "deno" },
  { name: "Bun", icon: "bun" },
  { name: "Deno Deploy", icon: "deno" },
  { name: "Railway", icon: "railway" },
  { name: "Render", icon: "render" },
  { name: "Fly.io", icon: "flydotio" },
  { name: "PlanetScale", icon: "planetscale" },
  { name: "Neon", icon: "neon" },
  { name: "Turso", icon: "turso" },
  { name: "Upstash", icon: "upstash" },
  { name: "Inngest", icon: "inngest" },
  { name: "Temporal", icon: "temporal" },
  { name: "Hasura", icon: "hasura" },
  { name: "Appwrite", icon: "appwrite" },
  { name: "PocketBase", icon: "pocketbase" },
  { name: "AWS Lambda", icon: "awslambda" },
  { name: "Google Cloud Functions", icon: "googlecloud" },
  { name: "Azure Functions", icon: "microsoftazure" },
  { name: "Cloudflare Workers", icon: "cloudflareworkers" },
  { name: "Vercel Edge Functions", icon: "vercel" },
  { name: "Netlify Functions", icon: "netlify" },
  { name: "Grafana", icon: "grafana" },
  { name: "Prometheus", icon: "prometheus" },
  { name: "Datadog", icon: "datadog" },
  { name: "New Relic", icon: "newrelic" },
  { name: "Sentry", icon: "sentry" },
  { name: "LogRocket", icon: "logrocket" },
  { name: "PostHog", icon: "posthog" },
  { name: "Mixpanel", icon: "mixpanel" },
  { name: "Amplitude", icon: "amplitude" },
  { name: "LaunchDarkly", icon: "launchdarkly" },
  { name: "Algolia", icon: "algolia" },
  { name: "Meilisearch", icon: "meilisearch" },
  { name: "Typesense", icon: "typesense" },
  { name: "Lodash", icon: "lodash" },
  { name: "Axios", icon: "axios" },
  { name: "Moment.js", icon: "momentdotjs" },
  { name: "Day.js", icon: "daydotjs" },
  { name: "date-fns", icon: "datefns" },
  { name: "Zod", icon: "zod" },
  { name: "Yup", icon: "yup" },
  { name: "Formik", icon: "formik" },
  { name: "React Hook Form", icon: "reacthookform" },
  { name: "TanStack Query", icon: "tanstackquery" },
  { name: "TanStack Router", icon: "tanstackrouter" },
  { name: "Zustand", icon: "zustand" },
  { name: "Jotai", icon: "jotai" },
  { name: "Recoil", icon: "recoil" },
  { name: "MobX", icon: "mobx" },
  { name: "Redux", icon: "redux" },
  { name: "Pinia", icon: "pinia" },
  { name: "Vuex", icon: "vuex" },
  { name: "Three.js", icon: "threedotjs" },
  { name: "D3.js", icon: "d3dotjs" },
  { name: "Chart.js", icon: "chartdotjs" },
  { name: "ECharts", icon: "apacheecharts" },
  { name: "Recharts", icon: "recharts" },
  { name: "Plotly", icon: "plotly" },
  { name: "Mapbox", icon: "mapbox" },
  { name: "Leaflet", icon: "leaflet" },
  { name: "OpenLayers", icon: "openlayers" },
  { name: "MapLibre", icon: "maplibre" },
  { name: "Babylon.js", icon: "babylonjs" },
  { name: "PlayCanvas", icon: "playcanvas" },
  { name: "PixiJS", icon: "pixi" },
  { name: "Phaser", icon: "phaser" },
  { name: "Unity", icon: "unity" },
  { name: "Unreal Engine", icon: "unrealengine" },
  { name: "Godot", icon: "godotengine" },
  { name: "Blender", icon: "blender" },
  { name: "Canva", icon: "canva" },
  { name: "Adobe XD", icon: "adobexd" },
  { name: "Sketch", icon: "sketch" },
  { name: "InVision", icon: "invision" },
  { name: "Principle", icon: "principle" },
  { name: "Framer", icon: "framer" },
  { name: "Webflow", icon: "webflow" },
  { name: "Bubble", icon: "bubble" },
  { name: "Retool", icon: "retool" },
  { name: "Appsmith", icon: "appsmith" },
  { name: "n8n", icon: "n8n" },
  { name: "Zapier", icon: "zapier" },
  { name: "IFTTT", icon: "ifttt" },
  { name: "Airtable", icon: "airtable" },
  { name: "Notion", icon: "notion" },
  { name: "Obsidian", icon: "obsidian" },
  { name: "Logseq", icon: "logseq" },
  { name: "Roam Research", icon: "roamresearch" },
  { name: "Craft", icon: "craft" },
  { name: "Bear", icon: "bear" },
  { name: "Ulysses", icon: "ulysses" },
  { name: "iA Writer", icon: "iawriter" },
  { name: "Typora", icon: "typora" },
  { name: "Mark Text", icon: "marktext" },
  { name: "HackMD", icon: "hackmd" },
  { name: "Outline", icon: "outline" },
  { name: "BookStack", icon: "bookstack" },
  { name: "Confluence", icon: "confluence" },
  { name: "Trello", icon: "trello" },
  { name: "Asana", icon: "asana" },
  { name: "Monday.com", icon: "mondaydotcom" },
  { name: "ClickUp", icon: "clickup" },
  { name: "Linear", icon: "linear" },
  { name: "Shortcut", icon: "shortcut" },
  { name: "Height", icon: "height" },
  { name: "Zenhub", icon: "zenhub" },
  { name: "GitKraken", icon: "gitkraken" },
  { name: "Sourcetree", icon: "sourcetree" },
  { name: "Tower", icon: "tower" },
  { name: "Fork", icon: "fork" },
  { name: "Sublime Text", icon: "sublimetext" },
  { name: "Atom", icon: "atom" },
  { name: "Emacs", icon: "gnuemacs" },
  { name: "Spacemacs", icon: "spacemacs" },
  { name: "Doom Emacs", icon: "doomemacs" },
  { name: "Kakoune", icon: "kakoune" },
  { name: "Helix", icon: "helix" },
  { name: "Zed", icon: "zed" },
  { name: "Lapce", icon: "lapce" },
  { name: "Fleet", icon: "jetbrainsfleet" },
  { name: "Warp", icon: "warp" },
  { name: "Alacritty", icon: "alacritty" },
  { name: "Kitty", icon: "kitty" },
  { name: "WezTerm", icon: "wezterm" },
  { name: "iTerm2", icon: "iterm2" },
  { name: "Hyper", icon: "hyper" },
  { name: "Tilix", icon: "tilix" },
  { name: "Terminology", icon: "terminology" },
  { name: "Cool Retro Term", icon: "coolretroterm" },
];

export const TEMPLATES: Template[] = [
  {
    name: "Minimal",
    description: "Clean and simple with just the essentials",
    icon: "Minimize2",
    config: {
      username: "",
      sections: [
        {
          id: "hero-min",
          type: "hero",
          title: "Hero",
          visible: true,
          data: {
            tagline: "",
            subtitle: "",
            showBranding: true,
            alignment: "center",
            showDivider: false,
          } as HeroData,
        },
        {
          id: "about-min",
          type: "about",
          title: "About",
          visible: true,
          data: { content: "" } as AboutData,
        },
      ],
    },
  },
  {
    name: "Developer",
    description: "Full developer profile with tech stack and GitHub stats",
    icon: "Code",
    config: {
      username: "",
      sections: [
        {
          id: "hero-dev",
          type: "hero",
          title: "Hero",
          visible: true,
          data: {
            tagline: "",
            subtitle: "",
            showBranding: true,
            alignment: "center",
            showDivider: false,
          } as HeroData,
        },
        {
          id: "about-dev",
          type: "about",
          title: "About",
          visible: true,
          data: { content: "" } as AboutData,
        },
        {
          id: "tech-dev",
          type: "tech-stack",
          title: "Tech Stack",
          visible: true,
          data: {
            groups: [{ id: "g1", title: "Tech Stack", items: [] }],
            displayStyle: "icons",
            gridColumns: 4,
            gridAlignment: "center",
            showLabels: true,
            iconSize: 40,
          } as TechStackData,
        },
        {
          id: "gh-dev",
          type: "github-widgets",
          title: "GitHub Widgets",
          visible: true,
          data: {
            stats: true,
            streak: true,
            languages: true,
            activity: true,
            theme: "transparent",
          } as GitHubWidgetsData,
        },
        {
          id: "social-dev",
          type: "social",
          title: "Social",
          visible: true,
          data: { links: [], style: "links", alignment: "center" } as SocialData,
        },
      ],
    },
  },
  {
    name: "Showcase",
    description: "Highlight features and tech for project READMEs",
    icon: "Monitor",
    config: {
      username: "",
      sections: [
        {
          id: "hero-show",
          type: "hero",
          title: "Hero",
          visible: true,
          data: {
            tagline: "",
            subtitle: "",
            showBranding: true,
            alignment: "center",
            showDivider: true,
          } as HeroData,
        },
        {
          id: "about-show",
          type: "about",
          title: "About",
          visible: true,
          data: { content: "" } as AboutData,
        },
        {
          id: "feat-show",
          type: "features",
          title: "Features",
          visible: true,
          data: {
            items: [],
            columns: 2,
            iconSize: "medium",
            showDescriptions: true,
          } as FeaturesData,
        },
        {
          id: "tech-show",
          type: "tech-stack",
          title: "Tech Stack",
          visible: true,
          data: {
            groups: [{ id: "g1", title: "Tech Stack", items: [] }],
            displayStyle: "grid",
            gridColumns: 4,
            gridAlignment: "center",
            showLabels: true,
            iconSize: 40,
          } as TechStackData,
        },
        {
          id: "gh-show",
          type: "github-widgets",
          title: "GitHub Widgets",
          visible: true,
          data: {
            stats: true,
            streak: false,
            languages: true,
            activity: true,
            theme: "dark",
          } as GitHubWidgetsData,
        },
      ],
    },
  },
  {
    name: "Creative",
    description: "Bold design for creative projects and portfolios",
    icon: "Palette",
    config: {
      username: "",
      sections: [
        {
          id: "hero-cre",
          type: "hero",
          title: "Hero",
          visible: true,
          data: {
            tagline: "",
            subtitle: "",
            showBranding: true,
            alignment: "left",
            showDivider: false,
          } as HeroData,
        },
        {
          id: "about-cre",
          type: "about",
          title: "About",
          visible: true,
          data: { content: "" } as AboutData,
        },
        {
          id: "feat-cre",
          type: "features",
          title: "Features",
          visible: true,
          data: {
            items: [],
            columns: 1,
            iconSize: "large",
            showDescriptions: true,
          } as FeaturesData,
        },
        {
          id: "tech-cre",
          type: "tech-stack",
          title: "Tech Stack",
          visible: true,
          data: {
            groups: [
              { id: "g1", title: "Frontend", items: [] },
              { id: "g2", title: "Design", items: [] },
            ],
            displayStyle: "list",
            gridColumns: 4,
            gridAlignment: "center",
            showLabels: true,
            iconSize: 24,
          } as TechStackData,
        },
        {
          id: "social-cre",
          type: "social",
          title: "Social",
          visible: true,
          data: { links: [], style: "badges", alignment: "center" } as SocialData,
        },
      ],
    },
  },
  {
    name: "Organization",
    description: "Professional template for teams and organizations",
    icon: "Building2",
    config: {
      username: "",
      sections: [
        {
          id: "hero-org",
          type: "hero",
          title: "Hero",
          visible: true,
          data: {
            tagline: "",
            subtitle: "",
            showBranding: true,
            alignment: "center",
            showDivider: true,
          } as HeroData,
        },
        {
          id: "about-org",
          type: "about",
          title: "About",
          visible: true,
          data: { content: "" } as AboutData,
        },
        {
          id: "feat-org",
          type: "features",
          title: "Features",
          visible: true,
          data: {
            items: [],
            columns: 3,
            iconSize: "medium",
            showDescriptions: true,
          } as FeaturesData,
        },
        {
          id: "gh-org",
          type: "github-widgets",
          title: "GitHub Widgets",
          visible: true,
          data: {
            stats: true,
            streak: false,
            languages: false,
            activity: true,
            theme: "flat",
          } as GitHubWidgetsData,
        },
        {
          id: "social-org",
          type: "social",
          title: "Social",
          visible: true,
          data: { links: [], style: "cards", alignment: "center" } as SocialData,
        },
      ],
    },
  },
  {
    name: "Blank",
    description: "Start from scratch with an empty canvas",
    icon: "FilePlus",
    config: {
      username: "",
      sections: [],
    },
  },
];

export const STORAGE_KEY = "repocanvas-config";

export function createDefaultSection(type: SectionType): import("@/types").Section {
  const id = `${type}-${Date.now().toString(36)}`;
  switch (type) {
    case "hero":
      return {
        id,
        type,
        title: SECTION_TYPES.hero.label,
        visible: true,
        data: {
          tagline: "",
          subtitle: "",
          showBranding: true,
          alignment: "center",
          showDivider: false,
        } as HeroData,
      };
    case "about":
      return {
        id,
        type,
        title: SECTION_TYPES.about.label,
        visible: true,
        data: { content: "" } as AboutData,
      };
    case "tech-stack":
      return {
        id,
        type,
        title: SECTION_TYPES["tech-stack"].label,
        visible: true,
        data: {
          groups: [{ id: `g-${id}`, title: "Tech Stack", items: [] }],
          displayStyle: "icons",
          gridColumns: 4,
          gridAlignment: "center",
          showLabels: true,
          iconSize: 40,
        } as TechStackData,
      };
    case "features":
      return {
        id,
        type,
        title: SECTION_TYPES.features.label,
        visible: true,
        data: {
          items: [],
          columns: 2,
          iconSize: "medium",
          showDescriptions: true,
        } as FeaturesData,
      };
    case "github-widgets":
      return {
        id,
        type,
        title: SECTION_TYPES["github-widgets"].label,
        visible: true,
        data: {
          stats: true,
          streak: true,
          languages: true,
          activity: true,
          theme: "transparent",
        } as GitHubWidgetsData,
      };
    case "social":
      return {
        id,
        type,
        title: SECTION_TYPES.social.label,
        visible: true,
        data: { links: [], style: "links", alignment: "center" } as SocialData,
      };
    case "visitor-counter":
      return {
        id,
        type,
        title: SECTION_TYPES["visitor-counter"].label,
        visible: true,
        data: { alignment: "center" } as VisitorCounterData,
      };
    case "trophies":
      return {
        id,
        type,
        title: SECTION_TYPES.trophies.label,
        visible: true,
        data: {
          theme: "default",
          alignment: "center",
          showRank: true,
        } as TrophiesData,
      };
    case "support":
      return {
        id,
        type,
        title: SECTION_TYPES.support.label,
        visible: true,
        data: { links: [], style: "badges", alignment: "center" } as SupportData,
      };
    case "fun-components":
      return {
        id,
        type,
        title: SECTION_TYPES["fun-components"].label,
        visible: true,
        data: { contentType: "both", alignment: "center" } as FunComponentsData,
      };
  }
}
